FROM python:3.9-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

ENV FLASK_APP=src/server.py
ENV FLASK_ENV=production

EXPOSE 8080

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "8080"]